"""agregar_puntos_experiencia_a_profesionales

Revision ID: 46608a703e02
Revises: fa2bcca873dc
Create Date: 2025-10-19 23:46:26.623129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46608a703e02'
down_revision: Union[str, None] = 'fa2bcca873dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Agregar la columna como nullable inicialmente
    op.add_column('profesionales', sa.Column('puntos_experiencia', sa.Integer(), nullable=True, comment='Puntos de experiencia acumulados por el profesional'))
    
    # 2. Actualizar todos los registros existentes con el valor por defecto
    op.execute("UPDATE profesionales SET puntos_experiencia = 0 WHERE puntos_experiencia IS NULL")
    
    # 3. Ahora hacer la columna NOT NULL
    op.alter_column('profesionales', 'puntos_experiencia', nullable=False, server_default='0')
    
    # 4. Crear el índice
    op.create_index(op.f('ix_profesionales_puntos_experiencia'), 'profesionales', ['puntos_experiencia'], unique=False)
    
    op.create_unique_constraint(None, 'resenas', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resenas', type_='unique')
    op.drop_index(op.f('ix_profesionales_puntos_experiencia'), table_name='profesionales')
    op.drop_column('profesionales', 'puntos_experiencia')
    # ### end Alembic commands ###
