"""agregar_payout_account_a_profesionales

Revision ID: 8d177745ec64
Revises: dfd278c9506f
Create Date: 2025-10-19 16:29:14.812333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d177745ec64'
down_revision: Union[str, None] = 'dfd278c9506f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profesionales', sa.Column('payout_account', sa.String(length=255), nullable=True, comment='CVU, CBU o Alias de Mercado Pago para pagos al profesional'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profesionales', 'payout_account')
    # ### end Alembic commands ###
