"""crear_tabla_trabajos_y_ofertas

Revision ID: af43297f6357
Revises: 8d177745ec64
Create Date: 2025-10-19 16:31:22.542511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af43297f6357'
down_revision: Union[str, None] = '8d177745ec64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas',
    sa.Column('profesional_id', sa.UUID(), nullable=False, comment='ID del profesional que hace la oferta'),
    sa.Column('cliente_id', sa.UUID(), nullable=False, comment='ID del cliente que recibe la oferta'),
    sa.Column('chat_id', sa.String(length=255), nullable=False, comment='ID de la sala de chat en Firestore donde se envió la oferta'),
    sa.Column('descripcion', sa.Text(), nullable=False, comment='Descripción detallada del servicio ofertado'),
    sa.Column('precio_final', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio final de la oferta en pesos argentinos'),
    sa.Column('estado', sa.Enum('OFERTADO', 'ACEPTADO', 'RECHAZADO', 'PAGADO', name='estado_oferta_enum'), nullable=False, comment='Estado actual de la oferta'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización del registro'),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profesional_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_ofertas_chat_id'), 'ofertas', ['chat_id'], unique=False)
    op.create_index(op.f('ix_ofertas_cliente_id'), 'ofertas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ofertas_estado'), 'ofertas', ['estado'], unique=False)
    op.create_index(op.f('ix_ofertas_profesional_id'), 'ofertas', ['profesional_id'], unique=False)
    op.create_table('trabajos',
    sa.Column('cliente_id', sa.UUID(), nullable=False, comment='ID del cliente que contrata el servicio'),
    sa.Column('profesional_id', sa.UUID(), nullable=False, comment='ID del profesional que ejecuta el servicio'),
    sa.Column('oferta_id', sa.UUID(), nullable=True, comment='ID de la oferta aceptada (Flujo Pro)'),
    sa.Column('servicio_instant_id', sa.UUID(), nullable=True, comment='ID del servicio instantáneo contratado (Flujo Instant)'),
    sa.Column('precio_final', sa.Numeric(precision=10, scale=2), nullable=False, comment='Monto total que pagó el cliente'),
    sa.Column('comision_plataforma', sa.Numeric(precision=10, scale=2), nullable=True, comment='Comisión que se queda la plataforma'),
    sa.Column('monto_liberado', sa.Numeric(precision=10, scale=2), nullable=True, comment='Monto que se le pagó al profesional'),
    sa.Column('estado_escrow', sa.Enum('PENDIENTE_PAGO', 'PAGADO_EN_ESCROW', 'LIBERADO', 'CANCELADO_REEMBOLSADO', name='estado_escrow_enum'), nullable=False, comment='Estado actual del dinero en el sistema de escrow'),
    sa.Column('mercadopago_payment_id', sa.String(length=255), nullable=True, comment='ID del pago en Mercado Pago'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización del registro'),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profesional_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_instant_id'], ['servicios_instantaneos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_trabajo_cliente_estado', 'trabajos', ['cliente_id', 'estado_escrow'], unique=False)
    op.create_index('idx_trabajo_estado_escrow', 'trabajos', ['estado_escrow'], unique=False)
    op.create_index('idx_trabajo_mp_payment', 'trabajos', ['mercadopago_payment_id'], unique=False)
    op.create_index('idx_trabajo_profesional_estado', 'trabajos', ['profesional_id', 'estado_escrow'], unique=False)
    op.create_index(op.f('ix_trabajos_cliente_id'), 'trabajos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_trabajos_estado_escrow'), 'trabajos', ['estado_escrow'], unique=False)
    op.create_index(op.f('ix_trabajos_mercadopago_payment_id'), 'trabajos', ['mercadopago_payment_id'], unique=True)
    op.create_index(op.f('ix_trabajos_oferta_id'), 'trabajos', ['oferta_id'], unique=False)
    op.create_index(op.f('ix_trabajos_profesional_id'), 'trabajos', ['profesional_id'], unique=False)
    op.create_index(op.f('ix_trabajos_servicio_instant_id'), 'trabajos', ['servicio_instant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trabajos_servicio_instant_id'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_profesional_id'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_oferta_id'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_mercadopago_payment_id'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_estado_escrow'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_cliente_id'), table_name='trabajos')
    op.drop_index('idx_trabajo_profesional_estado', table_name='trabajos')
    op.drop_index('idx_trabajo_mp_payment', table_name='trabajos')
    op.drop_index('idx_trabajo_estado_escrow', table_name='trabajos')
    op.drop_index('idx_trabajo_cliente_estado', table_name='trabajos')
    op.drop_table('trabajos')
    op.drop_index(op.f('ix_ofertas_profesional_id'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_estado'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_cliente_id'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_chat_id'), table_name='ofertas')
    op.drop_table('ofertas')
    # ### end Alembic commands ###
