"""Agregar acepta_instant y tarifa_por_hora a profesionales

Revision ID: f6524e102be2
Revises: a712bab2b239
Create Date: 2025-10-18 16:32:12.384059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6524e102be2'
down_revision: Union[str, None] = 'a712bab2b239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columna con valor por defecto temporal
    op.add_column('profesionales', sa.Column('acepta_instant', sa.Boolean(), server_default='false', nullable=False, comment='Si el profesional acepta trabajos instantáneos (sin agendamiento previo)'))
    op.add_column('profesionales', sa.Column('tarifa_por_hora', sa.Numeric(precision=10, scale=2), nullable=True, comment='Tarifa por hora del profesional (en moneda local, puede ser null si no configurada)'))
    op.create_unique_constraint(None, 'profesionales', ['id'])
    op.create_unique_constraint(None, 'usuarios', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_constraint(None, 'profesionales', type_='unique')
    op.drop_column('profesionales', 'tarifa_por_hora')
    op.drop_column('profesionales', 'acepta_instant')
    # ### end Alembic commands ###
