"""agregar_tabla_oficios_y_relacion_m2m

Revision ID: fdb5e492f8c5
Revises: f6524e102be2
Create Date: 2025-10-18 16:39:49.796885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb5e492f8c5'
down_revision: Union[str, None] = 'f6524e102be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oficios',
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre del oficio (ej: Plomería, Electricidad)'),
    sa.Column('descripcion', sa.String(length=500), nullable=True, comment='Descripción del oficio'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización del registro'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_oficios_nombre'), 'oficios', ['nombre'], unique=True)
    op.create_table('profesional_oficios',
    sa.Column('profesional_id', sa.UUID(), nullable=False, comment='ID del profesional'),
    sa.Column('oficio_id', sa.UUID(), nullable=False, comment='ID del oficio'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profesional_id', 'oficio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profesional_oficios')
    op.drop_index(op.f('ix_oficios_nombre'), table_name='oficios')
    op.drop_table('oficios')
    # ### end Alembic commands ###
