"""agregar_sistema_infracciones_chat

Revision ID: 0a294fb5a050
Revises: cdf610bcb5d4
Create Date: 2025-10-18 20:59:58.794180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a294fb5a050'
down_revision: Union[str, None] = 'cdf610bcb5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'portfolio_imagenes', ['id'])
    op.create_unique_constraint(None, 'portfolio_items', ['id'])
    op.create_unique_constraint(None, 'servicios_instantaneos', ['id'])
    op.add_column('usuarios', sa.Column('infracciones_chat', sa.Integer(), nullable=False, server_default='0', comment='Contador de infracciones en el chat (intento de pasar datos de contacto)'))
    op.add_column('usuarios', sa.Column('is_chat_banned', sa.Boolean(), nullable=False, server_default='false', comment='Indica si el usuario está baneado del chat por infracciones'))
    op.create_index(op.f('ix_usuarios_is_chat_banned'), 'usuarios', ['is_chat_banned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_is_chat_banned'), table_name='usuarios')
    op.drop_column('usuarios', 'is_chat_banned')
    op.drop_column('usuarios', 'infracciones_chat')
    op.drop_constraint(None, 'servicios_instantaneos', type_='unique')
    op.drop_constraint(None, 'portfolio_items', type_='unique')
    op.drop_constraint(None, 'portfolio_imagenes', type_='unique')
    # ### end Alembic commands ###
