"""agregar_servicios_instantaneos

Revision ID: 3278cf337f2c
Revises: 447eb6c4aea5
Create Date: 2025-10-18 16:53:45.833642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3278cf337f2c'
down_revision: Union[str, None] = '447eb6c4aea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
