"""agregar_avatar_url_a_usuarios

Revision ID: 447eb6c4aea5
Revises: fdb5e492f8c5
Create Date: 2025-10-18 16:51:17.325391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447eb6c4aea5'
down_revision: Union[str, None] = 'fdb5e492f8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'oficios', ['id'])
    op.add_column('usuarios', sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='URL o ruta del avatar del usuario'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'avatar_url')
    op.drop_constraint(None, 'oficios', type_='unique')
    # ### end Alembic commands ###
