"""agregar_portfolio_items_e_imagenes

Revision ID: cdf610bcb5d4
Revises: 3278cf337f2c
Create Date: 2025-10-18 16:59:29.611014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf610bcb5d4'
down_revision: Union[str, None] = '3278cf337f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios_instantaneos',
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre del servicio instantáneo (ej: Colgar un cuadro)'),
    sa.Column('descripcion', sa.String(length=500), nullable=True, comment='Descripción del servicio instantáneo'),
    sa.Column('oficio_id', sa.UUID(), nullable=False, comment='ID del oficio al que pertenece este servicio'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización del registro'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_servicios_instantaneos_nombre'), 'servicios_instantaneos', ['nombre'], unique=False)
    op.create_index(op.f('ix_servicios_instantaneos_oficio_id'), 'servicios_instantaneos', ['oficio_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('profesional_id', sa.UUID(), nullable=False, comment='ID del profesional dueño del portfolio'),
    sa.Column('titulo', sa.String(length=200), nullable=False, comment='Título del trabajo realizado'),
    sa.Column('descripcion', sa.String(length=1000), nullable=True, comment='Descripción detallada del trabajo'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización del registro'),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_profesional_id'), 'portfolio_items', ['profesional_id'], unique=False)
    op.create_table('profesional_servicios_instant',
    sa.Column('profesional_id', sa.UUID(), nullable=False, comment='ID del profesional'),
    sa.Column('servicio_id', sa.UUID(), nullable=False, comment='ID del servicio instantáneo'),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios_instantaneos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profesional_id', 'servicio_id')
    )
    op.create_table('portfolio_imagenes',
    sa.Column('portfolio_item_id', sa.UUID(), nullable=False, comment='ID del item de portfolio al que pertenece'),
    sa.Column('imagen_url', sa.String(length=500), nullable=False, comment='URL o ruta de la imagen'),
    sa.Column('orden', sa.Integer(), nullable=False, comment='Orden de visualización de la imagen'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal'),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización del registro'),
    sa.ForeignKeyConstraint(['portfolio_item_id'], ['portfolio_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_imagenes_portfolio_item_id'), 'portfolio_imagenes', ['portfolio_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_imagenes_portfolio_item_id'), table_name='portfolio_imagenes')
    op.drop_table('portfolio_imagenes')
    op.drop_table('profesional_servicios_instant')
    op.drop_index(op.f('ix_portfolio_items_profesional_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_servicios_instantaneos_oficio_id'), table_name='servicios_instantaneos')
    op.drop_index(op.f('ix_servicios_instantaneos_nombre'), table_name='servicios_instantaneos')
    op.drop_table('servicios_instantaneos')
    # ### end Alembic commands ###
